name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  shared_preferences: ^2.2.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/login-page/images/undrawwanderingmindrex2a3-1.png
    - assets/login-page/images/pakuwon-mall-1-bg.png
    - assets/login-page/images/pakuwon-mall-1-bg-gAd.png
    - assets/login-page/images/pakuwon-mall-1-bg-FkD.png
    - assets/login-page/images/undrawshoppingbagsnoba-1.png
    - assets/login-page/images/xiaomi.png
    - assets/login-page/images/profile-pic-bg.png
    - assets/login-page/images/icons.png
    - assets/login-page/images/rectangle-22-bg.png
    - assets/login-page/images/rectangle-bg.png
    - assets/login-page/images/rectangle-26.png
    - assets/login-page/images/.png
    - assets/login-page/images/icons-BNZ.png
    - assets/login-page/images/shihlin-logo-1.png
    - assets/login-page/images/icons-obP.png
    - assets/login-page/images/image-14-bg.png
    - assets/login-page/images/icons-ag1.png
    - assets/login-page/images/voucher.png
    - assets/login-page/images/icons-sAZ.png
    - assets/login-page/images/icons-RSy.png
    - assets/login-page/images/pencil-logo.png
    - assets/login-page/images/image-45.png
    - assets/login-page/images/image-7.png
    - assets/login-page/images/ellipse-5.png
    - assets/login-page/images/message-2-512-1.png
    - assets/login-page/images/profile-picture-bg.png
    - assets/login-page/images/rectangle-bg-Lqo.png
    - assets/login-page/images/image-3.png
    - assets/login-page/images/coin-barcode.png
    - assets/login-page/images/icons-fTw.png
    - assets/login-page/images/icons-bsP.png
    - assets/login-page/images/-A9o.png
    - assets/login-page/images/vertical-voucher-1.png
    - assets/login-page/images/xxi-1.png
    - assets/login-page/images/icons-BfP.png
    - assets/login-page/images/vertical-voucher-3.png
    - assets/login-page/images/central-mall-logo-1-2.png
    - assets/login-page/images/coin-barcode-bhb.png
    - assets/login-page/images/pngwing-1.png
    - assets/login-page/images/central-mall-logo-1-1-bg.png
    - assets/login-page/images/voucher-2.png
    - assets/login-page/images/image-43.png
    - assets/login-page/images/coin-barcode-rPj.png
    - assets/login-page/images/coin-barcode-c81.png
    - assets/login-page/images/citypng-1.png
    - assets/login-page/images/rectangle.png
    - assets/login-page/images/money-logo.png
    - assets/login-page/images/central-mall-logo-1-3.png
    - assets/login-page/images/central-mall-logo-1-1.png
    - assets/login-page/images/rectangle-26-bg.png
    - assets/login-page/images/vertical-voucher-2.png
    - assets/login-page/images/voucher-1.png
    - assets/login-page/images/starbucks-1.png
    - assets/login-page/images/-yaq.png
    - assets/login-page/images/rectangle-26-bg-t1X.png
    - assets/login-page/images/rectangle-26-Pus.png
    - assets/main-menu/images/central-mall-logo-1-2.png
    - assets/main-menu/images/image-3.png
    - assets/login-page/images/undrawshoppingbagsnoba-1.png
    - assets/main-menu/images/image-46.png
    - assets/main-menu/images/image-14-bg.png
    - assets/login-page/images/undrawwanderingmindrex2a3-1.png
    - assets/main-menu/images/message-2-512-1.png
    - assets/main-menu/images/voucher.png
    - assets/main-menu/images/frame-183.png
    - assets/main-menu/images/icons.png
    - assets/main-menu/images/pngwing-2.png
    - assets/main-menu/images/rectangle-bg.png
    - assets/main-menu/images/coin-barcode.png
    - assets/main-menu/images/voucher-LKs.png
    - assets/main-menu/images/xxi-1.png
    - assets/main-menu/images/image-3-Gtq.png
    - assets/main-menu/images/citypng-1.png
    - assets/main-menu/images/rectangle-bg-6Vw.png
    - assets/main-menu/images/central-mall-logo-1-2.png
    - assets/main-menu/images/.png
    - assets/main-menu/images/image-43.png
    - assets/main-menu/images/image-45.png
    - assets/main-menu/images/central-mall-logo-1-3.png
    - assets/main-menu/images/coin-barcode-AZf.png
    - assets/main-menu/images/icons-XU5.png
    - assets/main-menu/images/coin-barcode-WWu.png
    - assets/main-menu/images/barcode-1.png
    - assets/main-menu/images/central-mall-logo-1-1-bg.png
    - assets/main-menu/images/-ExR.png
    - assets/main-menu/images/profile-pic-bg.png
    - assets/main-menu/images/icons-KEy.png
    - assets/main-menu/images/icons-fJq.png
    - assets/main-menu/images/shihlin-logo-1.png
    - assets/main-menu/images/profile-picture-bg.png
    - assets/main-menu/images/icons-KNZ.png
    - assets/login-page/images/central-mall-logo-1-1.png
    - assets/main-menu/images/coin-barcode-Ufs.png
    - assets/main-menu/images/icons-u7w.png
    - assets/main-menu/images/rectangle-26-bg.png
    - assets/main-menu/images/central-mall-logo-1-4.png
    - assets/main-menu/images/rectangle-26-bg-oSZ.png
    - assets/main-menu/images/vertical-voucher-2.png
    - assets/main-menu/images/vertical-voucher-1.png
    - assets/main-menu/images/rectangle-22-bg.png
    - assets/main-menu/images/pencil-logo.png
    - assets/login-page/images/pakuwon-mall-1-bg.png
    - assets/login-page/images/pakuwon-mall-1-bg-Vc5.png
    - assets/login-page/images/pakuwon-mall-1-bg-7vH.png
    - assets/main-menu/images/icons-BgV.png
    - assets/main-menu/images/rectangle-26.png
    - assets/main-menu/images/xiaomi.png
    - assets/login-page/images/pakuwon-mall-1-bg-5iH.png
    - assets/main-menu/images/voucher-1.png
    - assets/main-menu/images/icons-qeh.png
    - assets/main-menu/images/starbucks-1.png
    - assets/login-page/images/pakuwon-mall-1-bg-fW1.png
    - assets/main-menu/images/pngwing-1.png
    - assets/main-menu/images/voucher-2.png
    - assets/main-menu/images/-BSh.png
    - assets/main-menu/images/icons-ur9.png
    - assets/main-menu/images/money-logo.png
    - assets/main-menu/images/ellipse-5.png
    - assets/main-menu/images/image-7.png
    - assets/main-menu/images/vertical-voucher-3.png
    - assets/main-menu/images/rectangle-26-1jX.png
    - assets/main-menu/images/-qDK.png
    - assets/main-menu/images/-qnq.png
    - assets/main-menu/images/rectangle-26-bg-VZb.png
    - assets/main-menu/images/rectangle-26-37X.png
    - assets/login-page/images/undrawshoppingbagsnoba-1.png
    - assets/main-menu/images/icons.png
    - assets/main-menu/images/icons-phF.png
    - assets/main-menu/images/ellipse-3.png
    - assets/main-menu/images/icons-Ct1.png
    - assets/main-menu/images/icons-oNZ.png
    - assets/main-menu/images/icons-CUZ.png
    - assets/login-page/images/central-mall-logo-1-1.png
    - assets/login-page/images/undrawwanderingmindrex2a3-1.png
    - assets/login-page/images/pakuwon-mall-1-bg.png
    - assets/main-menu/images/coin-barcode.png
    - assets/main-menu/images/gambar-dompet.png
    - assets/main-menu/images/icon-panah-bg.png
    - assets/main-menu/images/barcode.png
    - assets/main-menu/images/coin-barcode-d1K.png
    - assets/main-menu/images/search-icon.png
    - assets/main-menu/images/gambar-voucher-main-menu-bg.png
    - assets/main-menu/images/xxi-1.png
    - assets/main-menu/images/voucher-1-welcome-screen.png
    - assets/main-menu/images/voucher-3-welcome-screen.png
    - assets/main-menu/images/horizontal-voucher-5-bg.png
    - assets/main-menu/images/vertical-voucher-3.png
    - assets/main-menu/images/xiaomi.png
    - assets/main-menu/images/qr-code.png
    - assets/main-menu/images/central-mall-logo-1-2.png
    - assets/main-menu/images/bell-icon.png
    - assets/main-menu/images/horizontal-main-menu-1.png
    - assets/main-menu/images/pencil-logo.png
    - assets/main-menu/images/profile-pic-bg.png
    - assets/main-menu/images/voucher-bbX.png
    - assets/main-menu/images/coin-barcode-a41.png
    - assets/main-menu/images/ellipse-4.png
    - assets/main-menu/images/vertical-voucher-2.png
    - assets/main-menu/images/vertical-voucher-1.png
    - assets/main-menu/images/vertical-voucher-4.png
    - assets/main-menu/images/vertical-voucher-5.png
    - assets/main-menu/images/vertical-voucher-6.png
    - assets/main-menu/images/starbucks-1.png
    - assets/main-menu/images/horizontal-main-menu-3.png
    - assets/main-menu/images/horizontal-voucher-4.png
    - assets/main-menu/images/money-logo.png
    - assets/main-menu/images/horizontal-voucher-1-bg.png
    - assets/main-menu/images/shihlin-logo-1.png
    - assets/main-menu/images/horizontal-voucher-3.png
    - assets/main-menu/images/pngwing-1.png
    - assets/main-menu/images/profile-picture-bg.png
    - assets/main-menu/images/horizontal-main-menu-2.png
    - assets/main-menu/images/horizontal-voucher-2-bg.png
    - assets/main-menu/images/voucher-2-welcome-screen.png
    - assets/main-menu/images/central-mall-logo-1-1-Zdb.png
    - assets/main-menu/images/horizontal-main-menu-4.png
    - assets/main-menu/images/xiaomi-1.png
    - assets/main-menu/images/starbucks.png
    - assets/main-menu/images/xxi.png
    - assets/main-menu/images/shihlin.png
    - assets/main-menu/images/points-1.png
    - assets/main-menu/images/points-1-GsB.png
    - assets/main-menu/images/points-1-QjT.png
    - assets/main-menu/images/points-1-fvH.png
    - assets/main-menu/images/Voucher-1x.png
    - assets/main-menu/images/Voucher-2x.png
    - assets/main-menu/images/Voucher-3x.png
    - assets/main-menu/images/Voucher-4x.png
    - assets/main-menu/images/Voucher-5x.png
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Italic-VariableFont_wght.ttf
        - asset: fonts/Montserrat-VariableFont_wght.ttf


    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Black.ttf
        - asset: fonts/SourceSansPro-BlackItalic.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
        - asset: fonts/SourceSansPro-BoldItalic.ttf
        - asset: fonts/SourceSansPro-ExtraLight.ttf
        - asset: fonts/SourceSansPro-ExtraLightItalic.ttf
        - asset: fonts/SourceSansPro-Italic.ttf
        - asset: fonts/SourceSansPro-Light.ttf
        - asset: fonts/SourceSansPro-LightItalic.ttf
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Semibold.ttf
        - asset: fonts/SourceSansPro-SemiboldItalic.ttf
        




  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
